version: '3.7'

services:
  balancer1:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    volumes:
      - ./nginx/balancer1.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: 'true'
      traefik.http.routers.balancer1.rule: Host(`balancer1.retailcrm.test`)
      traefik.http.routers.balancer1.entrypoints: web

  balancer2:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    volumes:
      - ./nginx/balancer2.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    labels:
      traefik.enable: 'true'
      traefik.http.routers.balancer2.rule: Host(`balancer2.retailcrm.test`)
      traefik.http.routers.balancer2.entrypoints: web

  app:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    labels:
      traefik.enable: 'true'
      traefik.http.routers.app.rule: Host(`app.retailcrm.test`)
      traefik.http.routers.app.entrypoints: web

  php:
    build: .
    working_dir: /var/www
    volumes:
      - .:/var/www
